apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  description: Production Environment
gke:
  cluster: projects/celestial-torus-444415-r6/locations/us-central1-c/clusters/cluster-2
